### PR TITLE
Major refactor to improve project structure with Python's packaging system

### PR DESCRIPTION
**Pull request by SunPowered**
This refactor does a few things to bring the project into a more
python focused structure.  The changes are fairly drastic and its good practice for you go through the changes, comment on anything that's unclear before merging,

The setup.py file that existed was the main script.  Unfortunately,
this is a special file with python's `setuptools` packager and renders its
use to be confusing the way it was implemented.

This patch moves the main logic into a distributable `new_albums` package.
This allows for a convenient `pip install .` for local installation. 
The script can be run with the standard python script runner: ie
`python -m new_albums`.   Additionally, a __main__.py file was
 included to take over the role of the primary script.

Environment variables can also be set in a `.env` file which is ignored from
the version control system.  I find this to be the easiest to work with secrets and the like

The data.fiat.py file was awkward to package up.  so I changed the way
we specify custom genres to accept/reject.  The example
file is used was turned into the default.  You can create a new .py file (currently it must be in the `new_albums` package, but that should be changed in the future to be more universal.

 You can set the filename using a new `FIAT_FILE` env var.

README also adjusted to match changes.

### CODE REVIEW

**Comment by riverscuomo** [comment]
@SunPowered 
I'm struggling to figure out how I can run this new version of `new_albums `from my script runner. My script runner is a script that runs every night, triggered by Window Task Scheduler, which in turn runs about 10-20 other scripts depending on the day of the week. I can also run it from the command line with an option `--module` to run one of the scripts.

After the merge of the latest PR, I can't run `new_albums `from the script runner anymore.  (Though I can run `new_albums `by itself from the command line).

Here is the code in the script runner that used to work with `new_albums`:

```
setup_module = importlib.import_module(
                    'setup', # name
                    '{base_path}\new_albums, # package
                )
setup_module.main()
```
Obviously importing the module named `setup` like that won't work anymore because removed the setup file. Indeed I get this error:

`setup:  error: option -m not recognized
`
I tried importing by 2 other names but both returned errors.

'main' gives me
`Failure to import new_albums. <No module named 'main'>
`

'__main__' gives me
` module '__main__' has no attribute 'main'
`
Any idea how I can run this new version of `new_albums `from another script?

**Comment by SunPowered** [comment]
Ok, looks like you are going to need to call the script a little differently from your Task Scheduler

You should be able to set up the call to `python -m new_albums` in  your scheduling script.  Something to the effect of 

```
import os
os.system("python -m new_albums")
```

I noticed the script has some points where user input could be required.  If you are keen on automating the script as you are here, this can lock up the task waiting for input it will never receive.  We should look into separating out these user input portions from the core functionality.

Will this suit you for the time being?

**Comment by SunPowered** [comment]
Just had another thought: 

The `main()` function now resides in the `new_albums/__main__.py` file, instead of `setup.py`  You can likely just update your task code to the following:

```
setup_module = importlib.import_module(
                    '__main__', # name
                    '{base_path}\new_albums\new_albums, # package
                )
setup_module.main()
```

I would personally still go with my first approach, but this should also get things running for you now

**Comment by riverscuomo** [comment]
Wow `os.system("python -m new_albums")` worked. That's much simpler than what I had.

But how do I get the return value from main now? My script runner sends me a report of the results of all the scripts and now `new_albums `is returning 0 instead of 
`return f"Success! {description}"`

image

**Comment by SunPowered** [comment]
If you need the script to return a formatted string, then calling `os.system` won't work on its own.  It just returns the exit code of the process (0 being all good). 

If you revert to the old way with the updated path (my 2nd comment), this should work for your needs.

Scripts are typically expected to be run from a shell, and so returning a value is not supported.  In your case, it's working, so let's leave it.  I can think of a few better ways to solve this.

**Pull request merged**
